[package]
name = "reconfix"
description = "bidirectional data transformation engine"
version = "0.3.0"
authors = ["Aaron Brodersen <aaron@resin.io>"]
license = "Apache-2.0"

[dev-dependencies]
env_logger = "0.4"

[dependencies]
log = "0.4"
serde = "1.0"
regex = "0.2"
error-chain = "0.11"
lazy_static = "^0.2"
maplit = "0.1"
futures = "0.1"

[dependencies.nom]
version = "3.0"
# features = ["verbose-errors"]

[dependencies.serde_json]
version = "1.0"
# features = ["linked-hash-map"]