[package]
name = "reconfix"
description = "bidirectional data transformation engine"
version = "0.1.0"
authors = ["Corey Richardson <corey@resin.io>"]
license = "Apache-2.0"

[dependencies]
serde = "1.0"
serde_json = "1.0"
regex = "0.2"
error-chain = "0.11"
lazy_static = "^0.2"
maplit = "0.1"
futures = "0.1"

[dependencies.nom]
version = "3.0"
# features = ["verbose-errors"]