unstable_features = true

max_width = 100
comment_width = 80
wrap_comments = true

match_block_trailing_comma = true
use_try_shorthand = true
use_field_init_shorthand = true

imports_indent = "Block"
force_multiline_blocks = true
